export const categories = [
  // "aardappel-groente-fruit",
  "salades-pizza-maaltijden",
  "vlees-kip-vis-vega",
  "kaas-vleeswaren-tapas",
  "zuivel-plantaardig-eieren",
  "bakkerij-en-banket",
  "ontbijtgranen-en-beleg",
  "snoep-koek-chips-en-chocolade",
  "tussendoortjes",
  "frisdrank-sappen-koffie-thee",
  "pasta-rijst-en-wereldkeuken",
  "soepen-sauzen-kruiden-olie",
  "sport-en-dieetvoeding",
  "diepvries",
  "drogisterij",
  "baby-en-kind",
  // "huishouden",
  "huisdier",
];
