module.exports = [
  // "verse-maaltijden-en-gemak",
  // "vlees,-vis,-vegetarisch",
  // "brood-en-gebak",
  // "vleeswaren,-kaas-en-tapas",
  // "zuivel,-eieren,-boter",
  // "conserven,-soepen,-sauzen,-olien",
  // "wereldkeukens,-kruiden,-pasta-en-rijst",
  // "ontbijt,-broodbeleg-en-bakproducten",
  // "koek,-snoep,-chocolade-en-chips",
  // "diepvries",
  "bakkerij",
  "kaas-vleeswaren-delicatessen",
  "zuivel-eieren",
  "verse-kant-en-klaar-maaltijden",
  "internationale-keuken",
  "soepen-conserven-smaakmakers",
  "ontbijt-beleg-bakken-granen",
  "snoep-koek-chips",
  "diepvries",
];
